-- Data Definition Uberk-eats

IF (NOT EXISTS (SELECT * 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'ROLES'))
BEGIN
    CREATE TABLE [ROLES](
		ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NAME VARCHAR(200) NOT NULL
	)
END
GO

IF (NOT EXISTS (SELECT * 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'USERS'))
BEGIN
    CREATE TABLE [USERS](
		ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NAME VARCHAR(100) NOT NULL,
		SURNAME VARCHAR(100) NOT NULL,
		MAIL VARCHAR(100) NOT NULL,
		PHONE VARCHAR(20) NOT NULL,
		PASSWORD VARCHAR(100) NOT NULL
	)
END
GO

IF (NOT EXISTS (SELECT * 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'USERROLES'))
BEGIN
    CREATE TABLE [USERROLES](
		USERID BIGINT NOT NULL FOREIGN KEY REFERENCES USERS(ID),
		ROLEID BIGINT NOT NULL FOREIGN KEY REFERENCES ROLES(ID)
	)
END
GO