-- Data Definition Uberk-eats

IF (NOT EXISTS (SELECT * 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'ROLE'))
BEGIN
    CREATE TABLE [ROLE](
		ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NAME VARCHAR(200) NOT NULL
	)
END
GO

IF (NOT EXISTS (SELECT * 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'USER'))
BEGIN
    CREATE TABLE [USER](
		ID BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
		NAME VARCHAR(100) NOT NULL,
		SURNAME VARCHAR(100) NOT NULL,
		MAIL VARCHAR(100) NOT NULL,
		PHONE VARCHAR(20) NOT NULL,
		PASSWORD VARCHAR(100) NOT NULL
	)
END
GO

IF (NOT EXISTS (SELECT * 
            FROM INFORMATION_SCHEMA.TABLES 
            WHERE TABLE_NAME = 'USERROLE'))
BEGIN
    CREATE TABLE [USERROLE](
		USERID BIGINT NOT NULL FOREIGN KEY REFERENCES [USER](ID) ON DELETE CASCADE,
		ROLEID BIGINT NOT NULL FOREIGN KEY REFERENCES [ROLE](ID) ON DELETE CASCADE
	)
END
GO