version: "1.0"
services:
  auth:
    build: .\Authentification
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    hostname: mssql
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27117:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  menu_ms:
    hostname: menuapi
    build: .\Microservices\menus
    ports:
      - 3000:3000
    depends_on:
      - mongo
    restart: always
  article_ms:
    build: .\Microservices\articles
    ports:
      - 3001:3001
    depends_on:
      - mongo
    restart: always
  connectionlogs_ms:
    build: .\Microservices\connectionLogs
    ports:
      - 3002:3002
    depends_on:
      - mongo
    restart: always  
  restaurant_ms:
    build: .\Microservices\restaurants
    ports:
      - 3003:3003
    depends_on:
      - mongo
    restart: always
  order_ms:
    build: .\Microservices\orders
    ports:
      - 3004:3004
    depends_on:
      - mongo
    restart: always
  kong-dbless:
    image: kong/kong-gateway:2.8.1.1-alpine
    volumes:
      - "./kong/declarative/:/kong/declarative/"
    environment:
      - "KONG_DATABASE=off"
      - "KONG_DECLARATIVE_CONFIG=/kong/declarative/kong.yml"
      - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_ADMIN_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
      - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
    ports:
      - 9000:8000
      - 9443:8443
      - 9001:8001
      - 9444:8444
      - 9002:8002
      - 9445:8445
      - 9003:8003
      - 9004:8004
