version: "1.0"
services:
  auth:
    build: .\Authentification
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - mssql
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
    hostname: mssql
  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - 27117:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root